export * from './types';
export { parseSvg } from './svg/parse';
export { parsePathData, flattenSubpaths } from './svg/pathData';
export { parseColor } from './svg/color';
export { flattenGeometry } from './svg/scene';
export { computeSdf, computeLayout, computeRows, prepareScene } from './sdf/compute';
export { packEdges } from './sdf/edges';
export { nearestOnCubic, monotonePieces } from './sdf/bezier';
export { metricMatrix, metricSetup, nearestL1Cubic, nearestL1Line, nearestLp, nearestPolygon } from './sdf/metrics';
export type { SdfOptions } from './sdf/compute';
export { SdfWorkerPool, CancelledError } from './sdf/workerPool';
export type { SdfJob } from './sdf/workerPool';
export { encodeSdf, decodeSdf } from './io/sdfFile';
